apiVersion: v1
kind: Pod
metadata:
  name: mcserver
  labels:
    name: mcserver
spec:
  containers:
    - name: mcserver
      image: sansyou47/mcserver:v1
      resources:
        limits:
          memory: "3000Mi"
          cpu: "1000m"
      ports:
        - containerPort: 25565
